#!/usr/bin/env python3
# ABOUTME: SessionStart hook — cheap imperative nudge advertising the `codemap` command for this repo
# ABOUTME: No generation, no ast-grep scan, no file; just tells the agent orientation is one command away

"""On-demand code map: awareness half. The map itself is generated by the
`codemap` CLI when the agent (or human) runs it, fresh at call time. This hook
only makes the agent aware the capability exists, using free structural facts
(detected stacks, workspace count) from a manifest sniff, NEVER an ast-grep
scan. Load-bearing because a passive command is invisible: an agent won't run
`codemap` unless told it's there. Imperative phrasing targets the moment the
agent would otherwise grep blind. Fail-open: any error exits 0, no output."""

import importlib.util
import json
import os
import subprocess
import sys

GENERATOR = os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "codemap", "generate.py")


def load_generator():
    spec = importlib.util.spec_from_file_location("codemap_generate", GENERATOR)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def is_git_repo(path):
    try:
        r = subprocess.run(
            ["git", "-C", path, "rev-parse", "--is-inside-work-tree"],
            capture_output=True, text=True, timeout=10,
        )
        return r.returncode == 0 and r.stdout.strip() == "true"
    except OSError:
        return False


def main():
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except json.JSONDecodeError:
        sys.exit(0)

    repo = payload.get("cwd") or os.getcwd()
    if not os.path.isdir(repo) or not is_git_repo(repo) or not os.path.isfile(GENERATOR):
        sys.exit(0)

    try:
        g = load_generator()
        info = g.structural_summary(repo)  # manifest sniff only, no ast-grep scan
    except Exception:
        sys.exit(0)

    if not info:
        sys.exit(0)  # nothing worth mapping

    print(
        f"This repo exposes HTTP/RPC surfaces ({info['summary']}). Before grepping to find where "
        f"routes, endpoints, or handlers live, run `codemap` in the terminal for a fresh "
        f"orientation map (endpoints, routes, workspaces, layout). For live symbol navigation "
        f"(who calls X, where Y is defined) use the LSP tools instead."
    )
    sys.exit(0)


if __name__ == "__main__":
    main()
